// Code generated by MockGen. DO NOT EDIT.
// Source: save.go
//
// Generated by this command:
//
//	mockgen -source save.go -destination save_mock.go -package save
//

// Package save is a generated GoMock package.
package save

import (
	context "context"
	reflect "reflect"

	filters "github.com/Servflow/servflow/pkg/engine/integration/integrations/filters"
	gomock "go.uber.org/mock/gomock"
)

// MocksaveIntegration is a mock of saveIntegration interface.
type MocksaveIntegration struct {
	ctrl     *gomock.Controller
	recorder *MocksaveIntegrationMockRecorder
}

// MocksaveIntegrationMockRecorder is the mock recorder for MocksaveIntegration.
type MocksaveIntegrationMockRecorder struct {
	mock *MocksaveIntegration
}

// NewMocksaveIntegration creates a new mock instance.
func NewMocksaveIntegration(ctrl *gomock.Controller) *MocksaveIntegration {
	mock := &MocksaveIntegration{ctrl: ctrl}
	mock.recorder = &MocksaveIntegrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksaveIntegration) EXPECT() *MocksaveIntegrationMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MocksaveIntegration) Store(ctx context.Context, data map[string]any, options map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, data, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MocksaveIntegrationMockRecorder) Store(ctx, data, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MocksaveIntegration)(nil).Store), ctx, data, options)
}

// Type mocks base method.
func (m *MocksaveIntegration) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MocksaveIntegrationMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MocksaveIntegration)(nil).Type))
}

// Update mocks base method.
func (m *MocksaveIntegration) Update(ctx context.Context, data map[string]any, options map[string]string, filter ...filters.Filter) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, data, options}
	for _, a := range filter {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MocksaveIntegrationMockRecorder) Update(ctx, data, options any, filter ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, data, options}, filter...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MocksaveIntegration)(nil).Update), varargs...)
}
