kind: pipeline
type: docker
name: servflow-ci-cd

platform:
  os: linux

services:
  - name: cache
    image: redis

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  - name: debug-docker
    image: docker
    privileged: true
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker version
      - docker info

  - name: wait-for-redis
    image: redis
    commands:
      - until redis-cli -h cache ping; do sleep 1; done

  - name: code-quality
    image: golang:1.25
    volumes:
      - name: deps
        path: /go
    commands:
      - go install honnef.co/go/tools/cmd/staticcheck@2025.1.1
      - gofmt -d .
      - if [ "$(gofmt -l .)" ]; then echo "Code not formatted properly"; exit 1; fi
      - staticcheck ./...

  - name: test
    image: golang:1.25
    privileged: true
    depends_on:
      - wait-for-redis
      - code-quality
    environment:
      DATABASE_URL: "user=postgres password=password host=database port=5432 dbname=postgres sslmode=disable"
      TESTCONTAINERS_RYUK_DISABLED: true
    volumes:
      - name: deps
        path: /go
      - name: shared-data
        path: /shared
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - go test ./...

volumes:
  - name: deps
    host:
      path: /var/lib/cache/drone/go
  - name: shared-data
    temp: {}
  - name: docker-sock
    host:
      path: /var/run/docker.sock
