// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source interfaces.go -destination binance_mocks.go -package binance
//

// Package binance is a generated GoMock package.
package binance

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPriceProvider is a mock of PriceProvider interface.
type MockPriceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPriceProviderMockRecorder
}

// MockPriceProviderMockRecorder is the mock recorder for MockPriceProvider.
type MockPriceProviderMockRecorder struct {
	mock *MockPriceProvider
}

// NewMockPriceProvider creates a new mock instance.
func NewMockPriceProvider(ctrl *gomock.Controller) *MockPriceProvider {
	mock := &MockPriceProvider{ctrl: ctrl}
	mock.recorder = &MockPriceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceProvider) EXPECT() *MockPriceProviderMockRecorder {
	return m.recorder
}

// Get24HrTicker mocks base method.
func (m *MockPriceProvider) Get24HrTicker(symbol string) (*TickerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get24HrTicker", symbol)
	ret0, _ := ret[0].(*TickerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get24HrTicker indicates an expected call of Get24HrTicker.
func (mr *MockPriceProviderMockRecorder) Get24HrTicker(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get24HrTicker", reflect.TypeOf((*MockPriceProvider)(nil).Get24HrTicker), symbol)
}

// GetCurrentPrice mocks base method.
func (m *MockPriceProvider) GetCurrentPrice(symbol string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice", symbol)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockPriceProviderMockRecorder) GetCurrentPrice(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockPriceProvider)(nil).GetCurrentPrice), symbol)
}

// GetHistoricalPrice mocks base method.
func (m *MockPriceProvider) GetHistoricalPrice(symbol, interval string, limit int) ([]*KlineData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalPrice", symbol, interval, limit)
	ret0, _ := ret[0].([]*KlineData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalPrice indicates an expected call of GetHistoricalPrice.
func (mr *MockPriceProviderMockRecorder) GetHistoricalPrice(symbol, interval, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalPrice", reflect.TypeOf((*MockPriceProvider)(nil).GetHistoricalPrice), symbol, interval, limit)
}

// Type mocks base method.
func (m *MockPriceProvider) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockPriceProviderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockPriceProvider)(nil).Type))
}

// MockTradeExecutor is a mock of TradeExecutor interface.
type MockTradeExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockTradeExecutorMockRecorder
}

// MockTradeExecutorMockRecorder is the mock recorder for MockTradeExecutor.
type MockTradeExecutorMockRecorder struct {
	mock *MockTradeExecutor
}

// NewMockTradeExecutor creates a new mock instance.
func NewMockTradeExecutor(ctrl *gomock.Controller) *MockTradeExecutor {
	mock := &MockTradeExecutor{ctrl: ctrl}
	mock.recorder = &MockTradeExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTradeExecutor) EXPECT() *MockTradeExecutorMockRecorder {
	return m.recorder
}

// GetOpenOrders mocks base method.
func (m *MockTradeExecutor) GetOpenOrders(symbol string) (*OpenOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrders", symbol)
	ret0, _ := ret[0].(*OpenOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrders indicates an expected call of GetOpenOrders.
func (mr *MockTradeExecutorMockRecorder) GetOpenOrders(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrders", reflect.TypeOf((*MockTradeExecutor)(nil).GetOpenOrders), symbol)
}

// GetOrderInfo mocks base method.
func (m *MockTradeExecutor) GetOrderInfo(symbol string, orderID int64) (*OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo", symbol, orderID)
	ret0, _ := ret[0].(*OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockTradeExecutorMockRecorder) GetOrderInfo(symbol, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockTradeExecutor)(nil).GetOrderInfo), symbol, orderID)
}

// PlaceLimitOrder mocks base method.
func (m *MockTradeExecutor) PlaceLimitOrder(symbol, side string, quantity, price float64, timeInForce string) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceLimitOrder", symbol, side, quantity, price, timeInForce)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceLimitOrder indicates an expected call of PlaceLimitOrder.
func (mr *MockTradeExecutorMockRecorder) PlaceLimitOrder(symbol, side, quantity, price, timeInForce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceLimitOrder", reflect.TypeOf((*MockTradeExecutor)(nil).PlaceLimitOrder), symbol, side, quantity, price, timeInForce)
}

// PlaceMarketOrder mocks base method.
func (m *MockTradeExecutor) PlaceMarketOrder(symbol, side string, quantity float64) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceMarketOrder", symbol, side, quantity)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceMarketOrder indicates an expected call of PlaceMarketOrder.
func (mr *MockTradeExecutorMockRecorder) PlaceMarketOrder(symbol, side, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceMarketOrder", reflect.TypeOf((*MockTradeExecutor)(nil).PlaceMarketOrder), symbol, side, quantity)
}

// PlaceSpotOrder mocks base method.
func (m *MockTradeExecutor) PlaceSpotOrder(symbol, side string, quantity, quoteOrderQty *float64, orderType string, price, stopPrice *float64, timeInForce string) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceSpotOrder", symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceSpotOrder indicates an expected call of PlaceSpotOrder.
func (mr *MockTradeExecutorMockRecorder) PlaceSpotOrder(symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceSpotOrder", reflect.TypeOf((*MockTradeExecutor)(nil).PlaceSpotOrder), symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce)
}

// Type mocks base method.
func (m *MockTradeExecutor) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockTradeExecutorMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTradeExecutor)(nil).Type))
}

// MockAccountProvider is a mock of AccountProvider interface.
type MockAccountProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAccountProviderMockRecorder
}

// MockAccountProviderMockRecorder is the mock recorder for MockAccountProvider.
type MockAccountProviderMockRecorder struct {
	mock *MockAccountProvider
}

// NewMockAccountProvider creates a new mock instance.
func NewMockAccountProvider(ctrl *gomock.Controller) *MockAccountProvider {
	mock := &MockAccountProvider{ctrl: ctrl}
	mock.recorder = &MockAccountProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountProvider) EXPECT() *MockAccountProviderMockRecorder {
	return m.recorder
}

// GetAccountBalance mocks base method.
func (m *MockAccountProvider) GetAccountBalance() (*AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance")
	ret0, _ := ret[0].(*AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockAccountProviderMockRecorder) GetAccountBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockAccountProvider)(nil).GetAccountBalance))
}

// Type mocks base method.
func (m *MockAccountProvider) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockAccountProviderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockAccountProvider)(nil).Type))
}

// MockFuturesTrader is a mock of FuturesTrader interface.
type MockFuturesTrader struct {
	ctrl     *gomock.Controller
	recorder *MockFuturesTraderMockRecorder
}

// MockFuturesTraderMockRecorder is the mock recorder for MockFuturesTrader.
type MockFuturesTraderMockRecorder struct {
	mock *MockFuturesTrader
}

// NewMockFuturesTrader creates a new mock instance.
func NewMockFuturesTrader(ctrl *gomock.Controller) *MockFuturesTrader {
	mock := &MockFuturesTrader{ctrl: ctrl}
	mock.recorder = &MockFuturesTraderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuturesTrader) EXPECT() *MockFuturesTraderMockRecorder {
	return m.recorder
}

// GetAllPositions mocks base method.
func (m *MockFuturesTrader) GetAllPositions(symbol string) (*PositionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPositions", symbol)
	ret0, _ := ret[0].(*PositionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPositions indicates an expected call of GetAllPositions.
func (mr *MockFuturesTraderMockRecorder) GetAllPositions(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPositions", reflect.TypeOf((*MockFuturesTrader)(nil).GetAllPositions), symbol)
}

// GetFuturesAccountInfo mocks base method.
func (m *MockFuturesTrader) GetFuturesAccountInfo() (*FuturesAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuturesAccountInfo")
	ret0, _ := ret[0].(*FuturesAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFuturesAccountInfo indicates an expected call of GetFuturesAccountInfo.
func (mr *MockFuturesTraderMockRecorder) GetFuturesAccountInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuturesAccountInfo", reflect.TypeOf((*MockFuturesTrader)(nil).GetFuturesAccountInfo))
}

// GetFuturesOpenOrders mocks base method.
func (m *MockFuturesTrader) GetFuturesOpenOrders(symbol string) (*FuturesOpenOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuturesOpenOrders", symbol)
	ret0, _ := ret[0].(*FuturesOpenOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFuturesOpenOrders indicates an expected call of GetFuturesOpenOrders.
func (mr *MockFuturesTraderMockRecorder) GetFuturesOpenOrders(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuturesOpenOrders", reflect.TypeOf((*MockFuturesTrader)(nil).GetFuturesOpenOrders), symbol)
}

// PlaceFuturesOrder mocks base method.
func (m *MockFuturesTrader) PlaceFuturesOrder(symbol, side string, quantity float64, orderType string, price *float64, timeInForce, positionSide string, reduceOnly bool) (*FuturesOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceFuturesOrder", symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly)
	ret0, _ := ret[0].(*FuturesOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceFuturesOrder indicates an expected call of PlaceFuturesOrder.
func (mr *MockFuturesTraderMockRecorder) PlaceFuturesOrder(symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceFuturesOrder", reflect.TypeOf((*MockFuturesTrader)(nil).PlaceFuturesOrder), symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly)
}

// SetLeverage mocks base method.
func (m *MockFuturesTrader) SetLeverage(symbol string, leverage int) (*LeverageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLeverage", symbol, leverage)
	ret0, _ := ret[0].(*LeverageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLeverage indicates an expected call of SetLeverage.
func (mr *MockFuturesTraderMockRecorder) SetLeverage(symbol, leverage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLeverage", reflect.TypeOf((*MockFuturesTrader)(nil).SetLeverage), symbol, leverage)
}

// Type mocks base method.
func (m *MockFuturesTrader) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockFuturesTraderMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockFuturesTrader)(nil).Type))
}

// MockIntegration is a mock of Integration interface.
type MockIntegration struct {
	ctrl     *gomock.Controller
	recorder *MockIntegrationMockRecorder
}

// MockIntegrationMockRecorder is the mock recorder for MockIntegration.
type MockIntegrationMockRecorder struct {
	mock *MockIntegration
}

// NewMockIntegration creates a new mock instance.
func NewMockIntegration(ctrl *gomock.Controller) *MockIntegration {
	mock := &MockIntegration{ctrl: ctrl}
	mock.recorder = &MockIntegrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntegration) EXPECT() *MockIntegrationMockRecorder {
	return m.recorder
}

// Get24HrTicker mocks base method.
func (m *MockIntegration) Get24HrTicker(symbol string) (*TickerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get24HrTicker", symbol)
	ret0, _ := ret[0].(*TickerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get24HrTicker indicates an expected call of Get24HrTicker.
func (mr *MockIntegrationMockRecorder) Get24HrTicker(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get24HrTicker", reflect.TypeOf((*MockIntegration)(nil).Get24HrTicker), symbol)
}

// GetAccountBalance mocks base method.
func (m *MockIntegration) GetAccountBalance() (*AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance")
	ret0, _ := ret[0].(*AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockIntegrationMockRecorder) GetAccountBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockIntegration)(nil).GetAccountBalance))
}

// GetAllPositions mocks base method.
func (m *MockIntegration) GetAllPositions(symbol string) (*PositionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPositions", symbol)
	ret0, _ := ret[0].(*PositionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPositions indicates an expected call of GetAllPositions.
func (mr *MockIntegrationMockRecorder) GetAllPositions(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPositions", reflect.TypeOf((*MockIntegration)(nil).GetAllPositions), symbol)
}

// GetCurrentPrice mocks base method.
func (m *MockIntegration) GetCurrentPrice(symbol string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice", symbol)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockIntegrationMockRecorder) GetCurrentPrice(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockIntegration)(nil).GetCurrentPrice), symbol)
}

// GetFuturesAccountInfo mocks base method.
func (m *MockIntegration) GetFuturesAccountInfo() (*FuturesAccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuturesAccountInfo")
	ret0, _ := ret[0].(*FuturesAccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFuturesAccountInfo indicates an expected call of GetFuturesAccountInfo.
func (mr *MockIntegrationMockRecorder) GetFuturesAccountInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuturesAccountInfo", reflect.TypeOf((*MockIntegration)(nil).GetFuturesAccountInfo))
}

// GetFuturesOpenOrders mocks base method.
func (m *MockIntegration) GetFuturesOpenOrders(symbol string) (*FuturesOpenOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFuturesOpenOrders", symbol)
	ret0, _ := ret[0].(*FuturesOpenOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFuturesOpenOrders indicates an expected call of GetFuturesOpenOrders.
func (mr *MockIntegrationMockRecorder) GetFuturesOpenOrders(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFuturesOpenOrders", reflect.TypeOf((*MockIntegration)(nil).GetFuturesOpenOrders), symbol)
}

// GetHistoricalPrice mocks base method.
func (m *MockIntegration) GetHistoricalPrice(symbol, interval string, limit int) ([]*KlineData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalPrice", symbol, interval, limit)
	ret0, _ := ret[0].([]*KlineData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalPrice indicates an expected call of GetHistoricalPrice.
func (mr *MockIntegrationMockRecorder) GetHistoricalPrice(symbol, interval, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalPrice", reflect.TypeOf((*MockIntegration)(nil).GetHistoricalPrice), symbol, interval, limit)
}

// GetOpenOrders mocks base method.
func (m *MockIntegration) GetOpenOrders(symbol string) (*OpenOrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOrders", symbol)
	ret0, _ := ret[0].(*OpenOrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOrders indicates an expected call of GetOpenOrders.
func (mr *MockIntegrationMockRecorder) GetOpenOrders(symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOrders", reflect.TypeOf((*MockIntegration)(nil).GetOpenOrders), symbol)
}

// GetOrderInfo mocks base method.
func (m *MockIntegration) GetOrderInfo(symbol string, orderID int64) (*OrderInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo", symbol, orderID)
	ret0, _ := ret[0].(*OrderInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockIntegrationMockRecorder) GetOrderInfo(symbol, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockIntegration)(nil).GetOrderInfo), symbol, orderID)
}

// PlaceFuturesOrder mocks base method.
func (m *MockIntegration) PlaceFuturesOrder(symbol, side string, quantity float64, orderType string, price *float64, timeInForce, positionSide string, reduceOnly bool) (*FuturesOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceFuturesOrder", symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly)
	ret0, _ := ret[0].(*FuturesOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceFuturesOrder indicates an expected call of PlaceFuturesOrder.
func (mr *MockIntegrationMockRecorder) PlaceFuturesOrder(symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceFuturesOrder", reflect.TypeOf((*MockIntegration)(nil).PlaceFuturesOrder), symbol, side, quantity, orderType, price, timeInForce, positionSide, reduceOnly)
}

// PlaceLimitOrder mocks base method.
func (m *MockIntegration) PlaceLimitOrder(symbol, side string, quantity, price float64, timeInForce string) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceLimitOrder", symbol, side, quantity, price, timeInForce)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceLimitOrder indicates an expected call of PlaceLimitOrder.
func (mr *MockIntegrationMockRecorder) PlaceLimitOrder(symbol, side, quantity, price, timeInForce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceLimitOrder", reflect.TypeOf((*MockIntegration)(nil).PlaceLimitOrder), symbol, side, quantity, price, timeInForce)
}

// PlaceMarketOrder mocks base method.
func (m *MockIntegration) PlaceMarketOrder(symbol, side string, quantity float64) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceMarketOrder", symbol, side, quantity)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceMarketOrder indicates an expected call of PlaceMarketOrder.
func (mr *MockIntegrationMockRecorder) PlaceMarketOrder(symbol, side, quantity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceMarketOrder", reflect.TypeOf((*MockIntegration)(nil).PlaceMarketOrder), symbol, side, quantity)
}

// PlaceSpotOrder mocks base method.
func (m *MockIntegration) PlaceSpotOrder(symbol, side string, quantity, quoteOrderQty *float64, orderType string, price, stopPrice *float64, timeInForce string) (*OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceSpotOrder", symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce)
	ret0, _ := ret[0].(*OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceSpotOrder indicates an expected call of PlaceSpotOrder.
func (mr *MockIntegrationMockRecorder) PlaceSpotOrder(symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceSpotOrder", reflect.TypeOf((*MockIntegration)(nil).PlaceSpotOrder), symbol, side, quantity, quoteOrderQty, orderType, price, stopPrice, timeInForce)
}

// SetLeverage mocks base method.
func (m *MockIntegration) SetLeverage(symbol string, leverage int) (*LeverageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLeverage", symbol, leverage)
	ret0, _ := ret[0].(*LeverageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLeverage indicates an expected call of SetLeverage.
func (mr *MockIntegrationMockRecorder) SetLeverage(symbol, leverage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLeverage", reflect.TypeOf((*MockIntegration)(nil).SetLeverage), symbol, leverage)
}

// Type mocks base method.
func (m *MockIntegration) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockIntegrationMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockIntegration)(nil).Type))
}
