// Code generated by MockGen. DO NOT EDIT.
// Source: executionstep.go
//
// Generated by this command:
//
//	mockgen -source executionstep.go -destination executionstep_mock.go -package plan
//

// Package plan is a generated GoMock package.
package plan

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStep is a mock of Step interface.
type MockStep struct {
	ctrl     *gomock.Controller
	recorder *MockStepMockRecorder
}

// MockStepMockRecorder is the mock recorder for MockStep.
type MockStepMockRecorder struct {
	mock *MockStep
}

// NewMockStep creates a new mock instance.
func NewMockStep(ctrl *gomock.Controller) *MockStep {
	mock := &MockStep{ctrl: ctrl}
	mock.recorder = &MockStepMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStep) EXPECT() *MockStepMockRecorder {
	return m.recorder
}

// execute mocks base method.
func (m *MockStep) execute(ctx context.Context) (*stepWrapper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "execute", ctx)
	ret0, _ := ret[0].(*stepWrapper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// execute indicates an expected call of execute.
func (mr *MockStepMockRecorder) execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "execute", reflect.TypeOf((*MockStep)(nil).execute), ctx)
}
