// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Servflow/servflow/pkg/engine/plan (interfaces: Replica)
//
// Generated by this command:
//
//	mockgen -destination=replica_mock.go -package=plan . Replica
//

// Package plan is a generated GoMock package.
package plan

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReplica is a mock of Replica interface.
type MockReplica struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaMockRecorder
}

// MockReplicaMockRecorder is the mock recorder for MockReplica.
type MockReplicaMockRecorder struct {
	mock *MockReplica
}

// NewMockReplica creates a new mock instance.
func NewMockReplica(ctrl *gomock.Controller) *MockReplica {
	mock := &MockReplica{ctrl: ctrl}
	mock.recorder = &MockReplicaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplica) EXPECT() *MockReplicaMockRecorder {
	return m.recorder
}

// ExecuteAction mocks base method.
func (m *MockReplica) ExecuteAction(arg0, arg1 string) (any, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteAction", arg0, arg1)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExecuteAction indicates an expected call of ExecuteAction.
func (mr *MockReplicaMockRecorder) ExecuteAction(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteAction", reflect.TypeOf((*MockReplica)(nil).ExecuteAction), arg0, arg1)
}
