// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package storage

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CustomMessageFormat struct {
	_tab flatbuffers.Table
}

func GetRootAsCustomMessageFormat(buf []byte, offset flatbuffers.UOffsetT) *CustomMessageFormat {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CustomMessageFormat{}
	x.Init(buf, n+offset)
	return x
}

func FinishCustomMessageFormatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCustomMessageFormat(buf []byte, offset flatbuffers.UOffsetT) *CustomMessageFormat {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CustomMessageFormat{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCustomMessageFormatBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CustomMessageFormat) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CustomMessageFormat) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CustomMessageFormat) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CustomMessageFormat) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CustomMessageFormatStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CustomMessageFormatAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func CustomMessageFormatAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func CustomMessageFormatEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
