// Code generated by MockGen. DO NOT EDIT.
// Source: secrets.go
//
// Generated by this command:
//
//	mockgen -source secrets.go -destination secrets_mock.go -package secrets
//

// Package secrets is a generated GoMock package.
package secrets

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecretStorage is a mock of SecretStorage interface.
type MockSecretStorage struct {
	ctrl     *gomock.Controller
	recorder *MockSecretStorageMockRecorder
}

// MockSecretStorageMockRecorder is the mock recorder for MockSecretStorage.
type MockSecretStorageMockRecorder struct {
	mock *MockSecretStorage
}

// NewMockSecretStorage creates a new mock instance.
func NewMockSecretStorage(ctrl *gomock.Controller) *MockSecretStorage {
	mock := &MockSecretStorage{ctrl: ctrl}
	mock.recorder = &MockSecretStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretStorage) EXPECT() *MockSecretStorageMockRecorder {
	return m.recorder
}

// AddSecret mocks base method.
func (m *MockSecretStorage) AddSecret(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddSecret", key, value)
}

// AddSecret indicates an expected call of AddSecret.
func (mr *MockSecretStorageMockRecorder) AddSecret(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecret", reflect.TypeOf((*MockSecretStorage)(nil).AddSecret), key, value)
}

// FetchSecret mocks base method.
func (m *MockSecretStorage) FetchSecret(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchSecret", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// FetchSecret indicates an expected call of FetchSecret.
func (mr *MockSecretStorageMockRecorder) FetchSecret(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchSecret", reflect.TypeOf((*MockSecretStorage)(nil).FetchSecret), key)
}
