// Code generated by MockGen. DO NOT EDIT.
// Source: dpl.go
//
// Generated by this command:
//
//	mockgen -source dpl.go -destination dpl_mocks.go -package requestctx
//

// Package requestctx is a generated GoMock package.
package requestctx
